### PR TITLE
Converge Art and Confusion sources - step 1

### PR DESCRIPTION
**Pull request by quozl**
- combine icons, screenshots, challenge scripts, and thumbnails,

- resolve minor differences that happened during previous merges.

See also https://github.com/sugarlabs/activity-turtle-confusion/pull/8

Yet to do;

* [x] subclass the activity instance in TurtleArtActivity.py,
* [ ] merge plugins,
* [x] resolve conflict in license metadata,
* [ ] test,
* [ ] merge,
* [ ] delete activity-turtle-confusion repository.

### CODE REVIEW

**Comment by quozl** [comment]
@walterbender, is the general approach acceptable?

@vipulgupta2048, your license assessment of Turtle Confusion was different to Turtle Art; see 0954ed8 for the difference.  Could you check your assessment?

@yashagrawal3, your port to GTK+ 3 seems reasonably healthy in further testing, but I did catch a log error about improper arguments, see 4313dfa.

@rdrsadhu, your README.md added to Turtle Confusion will need to merge with the README.md here, are you able to do that?  The end game for this convergence is that the source repository will contain two activities, something we're used to already with the TamTam group of activities.

@chimosky, your pending pull requests for GLib and flake8 may conflict, and you haven't pushed to this branch, so I'll look into cherry picking your commits.

**Comment by walterbender** [comment]
@quozl  the subclass approach is the right way to go. Thx

**Comment by quozl** [comment]
Fixes https://github.com/sugarlabs/turtleart-activity/issues/66

**Comment by quozl** [comment]
Not proceeding, too much other work to do.  Abandoning Confusion.

**Pull request closed without merging**
