### PR TITLE
Updating 'tasprite_factory.js' translate from js

### PR DESCRIPTION
**Pull request by cristian99garcia**

### CODE REVIEW

**Comment by walterbender** [comment]
I am running into an import error when I am trying to run from your branch:

Traceback (most recent call last):
  File "./turtleblocks", line 21, in <module>
    from TurtleArt import turtleblocks
  File "/home/walter/activity-turtleart-gtk2/TurtleArt/turtleblocks.py", line 60, in <module>
    from TurtleArt.tawindow import TurtleArtWindow
  File "/home/walter/activity-turtleart-gtk2/TurtleArt/tawindow.py", line 106, in <module>
    from .talogo import (LogoCode, logoerror)
  File "/home/walter/activity-turtleart-gtk2/TurtleArt/talogo.py", line 45, in <module>
    from .tablock import (Block, Media, media_blocks_dictionary)
  File "/home/walter/activity-turtleart-gtk2/TurtleArt/tablock.py", line 32, in <module>
    from .tasprite_factory import (SVG, svg_str_to_pixbuf)
ImportError: cannot import name svg_str_to_pixbuf

**Comment by walterbender** [comment]
Still another small problem
File "/home/walter/activity-turtleart-gtk2/TurtleArt/taturtle.py", line 52, in generate_turtle_pixbufs
    shapes.append(svg_str_to_pixbuf(svg.turtle(colors)))
AttributeError: SVG instance has no attribute 'turtle'

**Comment by cristian99garcia** [comment]
Fixed, but more problems appeared:
tasprite_factory.py line 1290:
glib.GError: Error writing

Any idea why?

**Comment by cristian99garcia** [comment]
glib.GError Fixed. Now run.

**Comment by walterbender** [comment]
I don't get any errors, but the artwork doesn't seem to match the JS artwork. What am I doing wrong?

**Comment by walterbender** [comment]
I am having problems again: File "/home/walter/activity-turtleart-gtk2/TurtleArt/tasprite_factory.py", line 1290, in svg_str_to_pixbuf
    pl.write(svg_string)
glib.GError: Error writing

**Comment by walterbender** [comment]
Hmm. The graphics are heading in the right direction, but something is wrong (See figure)
screenshot from 2016-11-30 11-55-53

**Comment by cristian99garcia** [comment]
And how should it look? Turtle Blocks Js does not work for me and I can not see it
captura de pantalla de 2016-11-30 14-13-23

**Comment by walterbender** [comment]
screenshot from 2016-11-30 12-27-22

Curious why TurtleJS doesn't work for you... Anything in the console? (We can make debugging TurtleJS a separate task)

In your implementation, the forward block has 3 inputs. Should only have 1. And it doesn't dock properly to the start block. I'll try to look into where things are going amiss.

**Comment by cristian99garcia** [comment]
I don't know what the problem might be.

Yes, an interesting log (because localization.ini exists).
captura de pantalla de 2016-11-30 14-32-55

**Comment by walterbender** [comment]
Weird all the cross-origin errors. Can you run it from https://walterbender.github.io/turtleblocksjs/index.html
?

**Comment by cristian99garcia** [comment]
I'm using ArchLinux, and yes, from that link works for me
captura de pantalla de 2016-11-30 14-51-33

**Comment by cristian99garcia** [comment]
When I fix a bug, 3 more appear...
captura de pantalla de 2016-11-30 18-40-57

**Comment by walterbender** [comment]
Let us put this on pause.  You have done a lot of great work on this. I will create another task to finish this up after I have a chance to dig in a bit deeper.

**Comment by cristian99garcia** [comment]
Ok, by the way, open "bucle" palette throws this error (all others palettes works):

Traceback (most recent call last):
  File "/home/broot/sugar-build/build/out/install/share/sugar/activities/activity-turtleart-gtk2/TurtleArt/tawindow.py", line 1233, in _buttonpress_cb
    self.button_press(event.get_state() & gtk.gdk.CONTROL_MASK, x, y)
  File "/home/broot/sugar-build/build/out/install/share/sugar/activities/activity-turtleart-gtk2/TurtleArt/tawindow.py", line 1301, in button_press
    elif self._check_for_anything_else(spr, x, y):
  File "/home/broot/sugar-build/build/out/install/share/sugar/activities/activity-turtleart-gtk2/TurtleArt/tawindow.py", line 1619, in _check_for_anything_else
    self._select_category(spr)
  File "/home/broot/sugar-build/build/out/install/share/sugar/activities/activity-turtleart-gtk2/TurtleArt/tawindow.py", line 1801, in _select_category
    self.show_palette(i)
  File "/home/broot/sugar-build/build/out/install/share/sugar/activities/activity-turtleart-gtk2/TurtleArt/tawindow.py", line 979, in show_palette
    self.show_toolbar_palette(n)
  File "/home/broot/sugar-build/build/out/install/share/sugar/activities/activity-turtleart-gtk2/TurtleArt/tawindow.py", line 1089, in show_toolbar_palette
    self.palette_views[n].create(regenerate=regenerate, show=show)
  File "/home/broot/sugar-build/build/out/install/share/sugar/activities/activity-turtleart-gtk2/TurtleArt/tapaletteview.py", line 64, in create
    self._create_proto_blocks()
  File "/home/broot/sugar-build/build/out/install/share/sugar/activities/activity-turtleart-gtk2/TurtleArt/tapaletteview.py", line 189, in _create_proto_blocks
    PALETTE_SCALE))
  File "/home/broot/sugar-build/build/out/install/share/sugar/activities/activity-turtleart-gtk2/TurtleArt/tablock.py", line 284, in __init__
    self._new_block_from_factory(sprite_list, x, y, copy_block)
  File "/home/broot/sugar-build/build/out/install/share/sugar/activities/activity-turtleart-gtk2/TurtleArt/tablock.py", line 625, in _new_block_from_factory
    self._make_block(self.svg)
  File "/home/broot/sugar-build/build/out/install/share/sugar/activities/activity-turtleart-gtk2/TurtleArt/tablock.py", line 769, in _make_block
    self._block_methods[k](svg)
  File "/home/broot/sugar-build/build/out/install/share/sugar/activities/activity-turtleart-gtk2/TurtleArt/tablock.py", line 1124, in _make_clamp_style
    ['flow', False, self.svg.docks[3][0],
IndexError: list index out of range

**Comment by pro-panda** [comment]
@walterbender, should this be closed?

**Comment by walterbender** [comment]
I think we need to start this effort from scratch. But I still think it is a worthwhile task: the JavaScript artwork is much fresher than the Python artwork.

**Pull request closed without merging**
