### PR TITLE
Port from GObject to Glib

### PR DESCRIPTION
**Pull request by chimosky**

### CODE REVIEW

**Comment by chimosky** [comment]
@quozl kindly review.

**Comment by quozl** [comment]
Please rebase on the branch associated with https://github.com/sugarlabs/turtleart-activity/pull/63 and push there.

**Comment by quozl** [comment]
0d250c7 was cherry-picked for https://github.com/sugarlabs/turtleart-activity/pull/63

**Comment by pro-panda** [comment]
Changes implemented in #63

**Pull request closed without merging**
